### ISSUE TITLE
Вкладки в документации

### ISSUE THREAD

**Issue by dapi** [bitzlato/baseapp#116]
1) Дока как есть
2) Swagger (interactive console)
3) wesboscket - отображение marktown-а с GitHub-да, со ссылкой на источник. На странице документации добавить ссылку на /swagger и websocket доку - https://github.com/bitzlato/peatio/blob/master/docs/api/websocket_api.md

**Comment by dapi** [comment]
![Screen Shot 2021-09-06 at 07 58 13](https://user-images.githubusercontent.com/31139/132162932-6f5f4842-8f96-4abf-8db8-454ed353df88.png)

**Comment by dapi** [comment]
PEATIO USER API V2 меняем на `BITZLATO USER API V2`

**Comment by dapi** [comment]
4. sandbox - дока и ссылка на market-sandbox.bitzlato.com

**Comment by c0gnize** [comment]
> 1. sandbox - дока и ссылка на market-sandbox.bitzlato.com

нужна дока

**Comment by dapi** [comment]
Закрываю. По sandbox будем делать в рамках поднятия самой песочницы
