### ISSUE TITLE
Compiling formatjs messages

### ISSUE THREAD

**Issue by trzmaxim** [bitzlato/baseapp#124]
![Снимок экрана 2021-09-08 в 12 00 46](https://user-images.githubusercontent.com/2435004/132479978-d1990ba7-552d-43c8-95d1-06ed11eae450.png)

```
[@formatjs/intl] "defaultRichTextElements" was specified but "message" was not pre-compiled. 
Please consider using "@formatjs/cli" to pre-compile your messages for performance.
For more details see https://formatjs.io/docs/getting-started/message-distribution
```

Необходимо разобраться, что нужно сделать и нужно ли.

**Comment by c0gnize** [comment]
@trzmaxim этот ворнинг появился после https://github.com/bitzlato/baseapp/commit/a2a7444408c6bc356ac8e2d279f8cdd5a99d8391
сейчас тега br уже нету, так что если удалить defaultRichTextElements, то и предупреждения не будет
