### ISSUE TITLE
Не даёт добавить бенефициара

### ISSUE THREAD

**Issue by dapi** [bitzlato/baseapp#13]
![Screen Shot 2021-07-08 at 12 51 03](https://user-images.githubusercontent.com/31139/124902100-4d2c7580-dfeb-11eb-8219-f5d40c737421.png)

**Comment by dapi** [comment]
1) Blockchain Address заенить на Bitzlato User Public Name.
2) Отключить проверку на blockchain если так стоит в настройках валюты

**Comment by dapi** [comment]
Нужна будет поддержка со стороны бакенда

**Comment by c0gnize** [comment]
> 1. Blockchain Address заенить на Bitzlato User Public Name.
#109
> 2. Отключить проверку на blockchain если так стоит в настройках валюты
на клиенте провери на блокчейн нет, сразу дергается запрос `/account/beneficiaries`

**Comment by c0gnize** [comment]
@dapi этот issue можно закрывать?

**Comment by c0gnize** [comment]
> > 1. Отключить проверку на blockchain если так стоит в настройках валюты
> 
> на клиенте провери на блокчейн нет, сразу дергается запрос `/account/beneficiaries`

оказывается есть в процессе редактирования текста

**Comment by c0gnize** [comment]
![2021-09-08 12 33 52](https://user-images.githubusercontent.com/12247182/132485247-d34740ab-8e86-4cda-bc48-5c8636f81944.jpg)
> бага, невбивается сюда Public name

![2021-09-08 12 33 43](https://user-images.githubusercontent.com/12247182/132485402-82be5aaa-2a41-41e6-a03b-1763b12a013a.jpg)
> тут WARNING!
