### ISSUE TITLE
Вынести API Documentation из реакт приложения

### ISSUE THREAD

**Issue by trzmaxim** [bitzlato/baseapp#147]
Вынести https://market.bitzlato.com/docs из реакт приложения

**Comment by c0gnize** [comment]
куда вынести-то?

**Comment by trzmaxim** [comment]
Это придется решить :)

**Comment by c0gnize** [comment]
Мне приходит на ум использовать go сервер (который в baseapp) или ruby в самом peatio

**Comment by trzmaxim** [comment]
Сейчас из-за изменений #116 увеличилось кол-во скриптов и время продовой сборки(на моем компе) с 52 сек увеличилось до 66 сек(25%).

Я предлагаю вынести этот раздел в отдельную репу, сделать для него свой билд и деплой и на вебсервере настроить отдачу на урл https://market.bitzlato.com/docs

**Comment by c0gnize** [comment]
У меня почему-то другая ситуация: 
- на коммите fbbe76936 (v0.0.12) сборка занимает - 44.58, 46.18, 45.34
- на последнем мастере - 41.6, 44.21, 40.84
т.е. время наоборот сократилось

**Comment by trzmaxim** [comment]
Может это твой M1 такой крутой 😃

я тестировал 2d123266ee4f090d44cd599959df74fa82955901 и 04795eeff73d52ee07d68a39f18745a282897cda
```
➜  web git:(2d123266) yarn build
yarn run v1.22.10
$ cross-env NODE_ENV=production NODE_OPTIONS=--max_old_space_size=4096 webpack --config ./webpack/production.ts
Hash: d6d93f860d565af08bbb
Version: webpack 4.46.0
Time: 50946ms
...
```
```
➜  web git:(04795eef) yarn build
yarn run v1.22.10
$ cross-env NODE_ENV=production NODE_OPTIONS=--max_old_space_size=4096 webpack --config ./webpack/production.ts
Hash: 1f00430aeec83c65e6ff
Version: webpack 4.46.0
Time: 64490ms
...
```

И деплой на s5
```
...
00:47 yarn_build
01 /tmp/baseapp_tmp/baseapp-s5/nvm-exec.sh yarn build
...
01 Now using node v16.6.1 (npm v7.20.3)
01 yarn run v1.22.5
01 $ cross-env NODE_ENV=production NODE_OPTIONS=--max_old_space_size=4096 webpack --config ./webpack/production.ts
...
01 Hash: 98de6d15d10bd30dfda4
01 Version: webpack 4.46.0
01 Time: 58425ms
...
```
```
...
01:07 yarn_build
01 /tmp/baseapp_tmp/baseapp-s5/nvm-exec.sh yarn build
...
01 Now using node v16.6.1 (npm v7.20.3)
01 yarn run v1.22.5
01 $ cross-env NODE_ENV=production NODE_OPTIONS=--max_old_space_size=4096 webpack --config ./webpack/production.ts
...
01 Hash: 47d72915f7e23f067d8c
01 Version: webpack 4.46.0
01 Time: 81766ms
...
```

**Comment by trzmaxim** [comment]
А вот на прод мастер быстро сбилдился за `42190ms`

**Comment by c0gnize** [comment]
Я неправильно смотрел время через `time yarn start`, да время увеличилось
