### ISSUE TITLE
По-человечески писать что адрес у бенефициара не валидный

### ISSUE THREAD

**Issue by dapi** [bitzlato/baseapp#162]
По-моему со стороны baseapp должна быть поддержка калидации эфировских адресов.

В блокчеене bitzlato, например работает валидация на уровне фронта. А для эфировсских блокчейнов невалидные адрес пропускается на бэк откуда приходит что он не может создастся и не понятно почему (само сообщение от бэка сделаю более понятным)

![Screen Shot 2021-09-23 at 15 57 25](https://user-images.githubusercontent.com/31139/134512862-911286c6-1655-4ef8-b879-74b36b4e0f7c.png)
![Screen Shot 2021-09-23 at 15 56 54](https://user-images.githubusercontent.com/31139/134512873-6c4268a8-686d-40ac-b3de-359f8bbffea1.png)

**Comment by c0gnize** [comment]
Сейчас на фронте используются свои регулярки для проверки. Но в openware/baseapp недавно начали использовать отдельный пакет `multicoin-address-validator` (https://github.com/openware/baseapp/pull/775). Надо стянуть стабилку
А для этого идишника можно просто добавить человечский перевод на клиенте

**Comment by dapi** [comment]
Я за пакет.

**Comment by dapi** [comment]
А вы как по blockchain-у можете узнать какой валидатор использовать? нужен какой-то спец ключик?

**Comment by c0gnize** [comment]
> А вы как по blockchain-у можете узнать какой валидатор использовать? нужен какой-то спец ключик?

например у `bnb-bep20` извлекается стандарт токена `bep20`, который мапится в валюту `eth`, по которому адрес уже и валидируется
