### ISSUE TITLE
Lock the market column when scrolling horizontally

### ISSUE THREAD

**Issue by c0gnize** [bitzlato/baseapp#214]
![telegram-cloud-photo-size-2-5416136700549248958-y](https://user-images.githubusercontent.com/12247182/136975633-64bb640d-8603-4a11-ad33-14c1784a450b.jpg)

**Comment by dapi** [comment]
@c0gnize  задача еще актуальна?

**Comment by c0gnize** [comment]
> @c0gnize задача еще актуальна?

Да

**Comment by c0gnize** [comment]
В некотрых случаях не помещаются числа.
Именно это имел ввиду когда говорил, что лучше переписать стили таблицы
<img width="388" alt="Screenshot 2022-02-12 at 16 07 27" src="https://user-images.githubusercontent.com/12247182/153713509-3ff62b1a-2623-4b48-b2d2-ea9d3c18c990.png">
