### ISSUE TITLE
Предоставить дизайнеру табличку цветов для кастомизации

### ISSUE THREAD

**Issue by dapi** [bitzlato/baseapp#25]

**Comment by c0gnize** [comment]
Базовые цвета для темной и светлой темы расположены в файлах:
- https://github.com/bitzlato/baseapp/blob/master/src/styles/themes/dark.pcss
- https://github.com/bitzlato/baseapp/blob/master/src/styles/themes/light.pcss

Заголовок | css-variable
-- | --
Main background | --rgb-main-background-color
Body background | --rgb-body-background-color
Header background | --rgb-header-background-color
Subheader background | --rgb-subheader-background-color
Dropdown background | --rgb-dropdown-background-color
Icons | --rgb-icons
Primary Call to action | --rgb-primary-cta-color
Contrast Call to action | --rgb-contrast-cta-color
Secondary Contrast CTA | --rgb-secondary-contrast-cta-color
CTA Layer | --rgb-cta-layer-color
System Green | --rgb-system-green
System Red | --rgb-system-red
System Yellow | --rgb-system-yellow
Asks color | --rgb-asks
Bids color | --rgb-bids
Primary text | --rgb-primary-text-color
Text contrast | --rgb-text-contrast-color
Input background | --rgb-input-background-color
Divider color | --rgb-divider-color
Shadow color | --rgb-shadow-color
Landing background | --rgb-landing-background-color
Password very strong | --rgb-strength-meter-very-strong

Потом они используются для создания конечных css-переменных в: 
https://github.com/bitzlato/baseapp/blob/master/src/styles/colors.pcss
Где к цвету добавляется альфа или используюется напрямую.
