### ISSUE TITLE
Требование о подтверждении email-а

### ISSUE THREAD

**Issue by dapi** [bitzlato/baseapp#279]
Когда от API прилетает ответ (401) с `errors: ['identity.session.auth0.email_not_verified']` (там еще лежит ключ email: EMAIL) то показывать пользователю окно с сообщением "Подтвердите email" и кнопкой "Подтвердил". Нажимая на кнопку происходит запрос к /me и если все ок - то идем дальше, если емайл не подтвержден то остаемся на странице.

**Comment by dapi** [comment]
Можно еще в этом окне давать ссылку на auth0 домен где можно запросить подтверждение емайла но я не знаю как где ее взять.

Следующим этапом сделаем автоматическое уведомление этого окошка когда пользователь подтверждает email

**Comment by c0gnize** [comment]
@dapi вроде как можно отправить повторно письмо для верификации - https://auth0.com/docs/api/management/v2#!/Jobs/post_verification_email

**Comment by dapi** [comment]
> @dapi вроде как можно отправить повторно письмо для верификации - https://auth0.com/docs/api/management/v2#!/Jobs/post_verification_email

Я так понимаю это наш сервер должен на их отправить?

**Comment by c0gnize** [comment]
> Я так понимаю это наш сервер должен на их отправить?
Не обязательно. Но для подобных запросов хорошо какой-нибудь таймаут организовать, чтобы не заспамить
