### ISSUE TITLE
Отказаться от sonic

### ISSUE THREAD

**Issue by dapi** [bitzlato/baseapp#300]
В корне сохранить Gemfile*, Capfile, config, .ruby-version
все из web перенести в корень

**Comment by dapi** [comment]
@vsemkov

**Comment by trzmaxim** [comment]
Только из web не переносите пока 🙏

**Comment by c0gnize** [comment]
> Только из web не переносите пока 🙏

+

**Comment by trzmaxim** [comment]
`web` лучше оставить как есть, иначе проблемы в `shared` папке могут быть
