### ISSUE TITLE
Fixes typescript errors

### ISSUE THREAD

**Issue by trzmaxim** [bitzlato/baseapp#331]
```sh
~/b/baseapp master ❱ yarn tsc
...


Found 936 errors.
```

1. Исправить ошибки
2. Добавить джобу на провеку типов в github actions

**Comment by c0gnize** [comment]
У меня вызывает вопросы `exactOptionalPropertyTypes` вроде бы правильная штука, но на практике больше головной боли добавляет

**Comment by trzmaxim** [comment]
А какие вопросы вызывает?

**Comment by c0gnize** [comment]
Ну посмотри например в NumberInput, в итоге просятся изменение `className` у `FormControl`

**Comment by trzmaxim** [comment]
Да, неприятно, придется игнорировать места, где мы не можем повлиять на библиотеку.
