### ISSUE TITLE
При добавлении депозита он падает вниз списка, а нужно чтобы на верх. Проверить списания.

### ISSUE THREAD

**Issue by dapi** [bitzlato/baseapp#5]
![Screen Shot 2021-07-05 at 12 45 25](https://user-images.githubusercontent.com/31139/124452346-f7f42800-dd8e-11eb-826b-484d5b521dff.png)

**Comment by dapi** [comment]
Когда сидишь в кошельке,  периодически крутится спиннер. Вроде подгрузка делается. Надо убедиться что оно подгружается правильно и подгружается вообще.

**Comment by c0gnize** [comment]
> Когда сидишь в кошельке, периодически крутится спиннер. Вроде подгрузка делается. Надо убедиться что оно подгружается правильно и подгружается вообще.

Реально подгружаются балланс и валюта по таймеру каждые `balancesFetchInterval`, но есть ли польза от показа крутилки вопрос.

**Comment by dapi** [comment]
Похоже что нету, не я один обратил на это внимание как на баг

**Comment by c0gnize** [comment]
> Похоже что нету, не я один обратил на это внимание как на баг

Уберу тогда эту крутилку
