### ISSUE TITLE
Отсутствуют линки на пополнение в мобильном варианте

### ISSUE THREAD

**Issue by dapi** [bitzlato/baseapp#6]

**Comment by dapi** [comment]
#[](url)
![photo_2021-07-05_13-41-12](https://user-images.githubusercontent.com/31139/124461983-e6644d80-dd99-11eb-993b-ba735a9d7042.jpg)
![photo_2021-07-05_13-41-17](https://user-images.githubusercontent.com/31139/124461999-e8c6a780-dd99-11eb-8341-a8449ecc64a9.jpg)
![Изображение вставлено в 2021-7-5 13-41](https://user-images.githubusercontent.com/31139/124462002-e95f3e00-dd99-11eb-9fa1-abcd426355a5.png)

**Comment by trzmaxim** [comment]
Не актуально. Закрою.
Сейчас на проде:
![Снимок экрана 2021-09-14 в 23 15 05](https://user-images.githubusercontent.com/2435004/133327535-1b310af6-c7e0-45fa-ba3f-cf93d33497de.png)
