### ISSUE TITLE
Списания которые находятся в процессе отмечаются как выполненные, хотя нужно писать что они в процессе

### ISSUE THREAD

**Issue by dapi** [bitzlato/baseapp#7]
![Screen Shot 2021-07-06 at 11 00 58](https://user-images.githubusercontent.com/31139/124564242-87f6a800-de49-11eb-9a20-75cf6ba93d63.png)

**Comment by c0gnize** [comment]
Это `processing` и `fee_processing`?

Всего там вариантов: `succeed, failed, accepted, collected, canceled, rejected, processing, fee_processing, prepared, invoiced, submitted, confirming, skipped, errored `

**Comment by dapi** [comment]
Похоже на то. Надо любой незнакомый показывать как НЕ выполненный

**Comment by c0gnize** [comment]
Статусы списаний полностью переделаны в #79
