### ISSUE TITLE
При попытке ввести незначительную сумму выходит невнятное сообщение об ошибке, надо писать по-человечески что сумма мала и какая минимальная

### ISSUE THREAD

**Issue by dapi** [bitzlato/baseapp#8]
![Screen Shot 2021-07-06 at 11 04 24](https://user-images.githubusercontent.com/31139/124564752-0c492b00-de4a-11eb-8ae6-c19704d3b46f.png)
https://sentry.io/share/issue/b940cff9bc1940d8857d52688c2d2a22/

**Comment by c0gnize** [comment]
![2021-09-08 12 30 11](https://user-images.githubusercontent.com/12247182/132484385-69b09fdb-dcb8-4708-b83c-6291f0511e1b.jpg)
