### ISSUE TITLE
Use monospaced font for the numbers

### ISSUE THREAD

**Issue by c0gnize** [bitzlato/baseapp#83]
![2021-08-24 16 04 17](https://user-images.githubusercontent.com/12247182/130621283-17cb94a1-3fb7-40b2-ac69-8efcae9dcba1.jpg)

**Comment by trzmaxim** [comment]
Это прям для всех чисел? или только для тех который на картинке?

**Comment by c0gnize** [comment]
оригинальное сообщение @dapi:
> Все числа лучше выводить моноширинным шрифтом, тогда них циферки будут в ряд и будет просто ставнивать и считать
